### PR TITLE
[serverless-logic-1.24.x] kogito-runtimes|examples-sources-zip: Fix POM files location

### PR DESCRIPTION
**Pull request by MarianMacik**
The structure of the sources zip is:
* openshift-serverless-logic-\<version\>-src
  * org.kie.kogito-kogito-runtimes-\<version\>
  * and so on

Changes already tested on pipelines.

### CODE REVIEW

**Comment by jstastny-cz** [comment]
I was changing that as part of #69, expecting it would be a quick one. I would suggest using aterisk.

**Comment by MarianMacik** [comment]
So should we merge this one with asterisk or should I close this one in favour of your PR?

**Comment by jstastny-cz** [comment]
Please do it as part of this PR (to have more organized history). there are also other opta* modules that this change would be good to make in (making it more general in all cases).

**Review by jstastny-cz — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
