### PR TITLE
[7.67.x] kogito-runtimes-project-sources: Include -Dproductized property to ev…

### PR DESCRIPTION
**Pull request by MarianMacik**
…ery module
Backport of #62.

### CODE REVIEW

**Review by jstastny-cz — APPROVED** [review]
LGTM, thanks.

**Comment by jstastny-cz** [comment]
Ah, it doesn't look good afterall - wrong target branch it seems.

**Comment by MarianMacik** [comment]
Should be good now, thanks for noticing.

**Review by jstastny-cz — APPROVED** [review]
LGTM, now for real. Thanks

**Pull request merged**
